#!/bin/bash

# setup_project_structure.sh
# Creates the standardized Rigour Vibe project structure
# Run this from your project root directory

set -e  # Exit on any error

echo "🏗️  Setting up Rigour Vibe project structure..."
echo ""

# Check if we're in the right location
if [ ! -d "rigour_vibe" ]; then
    echo "❌ Error: This script should be run from the project root (where rigour_vibe/ exists)"
    echo "   Current directory: $(pwd)"
    exit 1
fi

echo "📁 Creating directory structure..."

# Core project directories
mkdir -p directives/{prd,spec,tasks,tests,summaries}
mkdir -p src/{core,api,ui,utils,config}
mkdir -p tests/{unit,integration,e2e,performance,fixtures}
mkdir -p build/{debug,release,docs}
mkdir -p scripts/{build,deploy,test,dev}
mkdir -p environment/{docker,conda,venv,ci}
mkdir -p docs/{api,user,dev}
mkdir -p assets/{images,fonts,data}
mkdir -p config/{development,staging,production}

echo "✅ Directory structure created successfully!"
echo ""

# Create basic README files for key directories
echo "📝 Creating directory documentation..."

# Directives README
cat > directives/README.md << 'EOF'
# Directives Directory

This directory contains all planning and tracking files generated by the Rigour Vibe framework.

## Subdirectories

- **prd/** - Product Requirements Documents for business features
- **spec/** - Technical Specifications for complex technical problems
- **tasks/** - Task breakdowns and implementation plans
- **tests/** - Test specifications, results, and coverage reports
- **summaries/** - Implementation summaries and progress reports

## File Naming Convention

Format: `YYYY-MM-DD_<filetype>_<feature-name>.md`

Examples:
- `2025-07-09_prd_user-authentication.md`
- `2025-07-09_spec_payment-api-integration.md`
- `2025-07-09_task_user-authentication.md`
- `2025-07-09_test_user-authentication_login-flow.md`
- `2025-07-09_summary_user-authentication_task-1-2.md`
EOF

# Environment README
cat > environment/README.md << 'EOF'
# Environment Directory

Contains environment configuration files for different deployment scenarios.

## Subdirectories

- **docker/** - Docker configurations (Dockerfile, docker-compose.yml)
- **conda/** - Conda environment files (environment.yml, requirements.txt)
- **venv/** - Virtual environment configurations
- **ci/** - CI/CD configuration files (GitHub Actions, etc.)

## Usage

Choose the appropriate environment configuration for your project:

- Use `docker/` for containerized deployments
- Use `conda/` for Python projects with conda environments
- Use `venv/` for Python projects with virtual environments
- Use `ci/` for continuous integration configurations
EOF

# Scripts README
cat > scripts/README.md << 'EOF'
# Scripts Directory

Contains automation and utility scripts for the project.

## Subdirectories

- **build/** - Build scripts and compilation automation
- **deploy/** - Deployment scripts and automation
- **test/** - Test execution scripts and test automation
- **dev/** - Development utility scripts

## Usage

Make scripts executable before running:
```bash
chmod +x scripts/build/build.sh
./scripts/build/build.sh
```
EOF

# Source README
cat > src/README.md << 'EOF'
# Source Directory

Contains all source code implementation files.

## Subdirectories

- **core/** - Business logic and core functionality
- **api/** - API endpoints and controllers
- **ui/** - User interface components
- **utils/** - Utility functions and helpers
- **config/** - Configuration and settings

## Organization

Organize files by feature within each subdirectory:
```
src/
├── core/
│   ├── authentication/
│   ├── user-management/
│   └── payment-processing/
├── api/
│   ├── auth/
│   ├── users/
│   └── payments/
└── ui/
    ├── auth/
    ├── profile/
    └── dashboard/
```
EOF

# Tests README
cat > tests/README.md << 'EOF'
# Tests Directory

Contains all test files organized by test type.

## Subdirectories

- **unit/** - Unit tests (isolated component testing)
- **integration/** - Integration tests (component interaction)
- **e2e/** - End-to-end tests (full workflow)
- **performance/** - Performance and load tests
- **fixtures/** - Test data and mock objects

## Organization

Mirror the src/ structure in each test subdirectory:
```
tests/
├── unit/
│   ├── core/
│   ├── api/
│   └── ui/
├── integration/
│   ├── auth-flow/
│   └── payment-flow/
└── fixtures/
    ├── users.json
    └── mock-api-responses.json
```
EOF

echo "✅ Directory documentation created!"
echo ""

# Create .gitkeep files in empty directories to ensure they're tracked
echo "📌 Adding .gitkeep files to empty directories..."

find . -type d -empty -not -path "./.git/*" -exec touch {}/.gitkeep \;

echo "✅ .gitkeep files added!"
echo ""

# Display the structure
echo "📋 Project structure created:"
echo ""
tree -a -I '.git' --dirsfirst . 2>/dev/null || find . -type d -not -path "./.git*" | sort

echo ""
echo "🎉 Rigour Vibe project structure setup complete!"
echo ""
echo "Next steps:"
echo "1. Start with: @rvb-create-prd.mdc or @rvb-create-spec.mdc"
echo "2. Generate tasks: @rvb-generate-tasks.mdc"
echo "3. Implement: @rvb-process-tasks.mdc"
echo ""
echo "All generated files will be automatically organized in the correct directories."
